# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: url.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'url.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\turl.proto\"q\n\tAccessLog\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x10\n\x08platform\x18\x04 \x01(\t\x12\x0f\n\x07\x62rowser\x18\x05 \x01(\t\x12\x14\n\x0c\x63lientDomain\x18\x06 \x01(\t\"\x95\x01\n\tUrlRecord\x12\x0f\n\x07\x66ullUrl\x18\x01 \x01(\t\x12\x10\n\x08shortUrl\x18\x02 \x01(\t\x12\x14\n\x0c\x63reationDate\x18\x03 \x01(\x03\x12\x13\n\x0b\x61\x63\x63\x65ssCount\x18\x04 \x01(\x05\x12\x1e\n\naccessLogs\x18\x05 \x03(\x0b\x32\n.AccessLog\x12\x1a\n\x12previewImageBase64\x18\x06 \x01(\t\"\'\n\x13ListUserUrlsRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"0\n\x14ListUserUrlsResponse\x12\x18\n\x04urls\x18\x01 \x03(\x0b\x32\n.UrlRecord\"?\n\x16\x43reateUrlRecordRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\"8\n\x17\x43reateUrlRecordResponse\x12\x1d\n\turlRecord\x18\x01 \x01(\x0b\x32\n.UrlRecord2\x97\x01\n\x12UrlExtendedService\x12;\n\x0cListUserUrls\x12\x14.ListUserUrlsRequest\x1a\x15.ListUserUrlsResponse\x12\x44\n\x0f\x43reateUrlRecord\x12\x17.CreateUrlRecordRequest\x1a\x18.CreateUrlRecordResponseB#\n\x0e\x65\x64u.pucmm.grpcB\x0fUrlServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'url_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016edu.pucmm.grpcB\017UrlServiceProtoP\001'
  _globals['_ACCESSLOG']._serialized_start=13
  _globals['_ACCESSLOG']._serialized_end=126
  _globals['_URLRECORD']._serialized_start=129
  _globals['_URLRECORD']._serialized_end=278
  _globals['_LISTUSERURLSREQUEST']._serialized_start=280
  _globals['_LISTUSERURLSREQUEST']._serialized_end=319
  _globals['_LISTUSERURLSRESPONSE']._serialized_start=321
  _globals['_LISTUSERURLSRESPONSE']._serialized_end=369
  _globals['_CREATEURLRECORDREQUEST']._serialized_start=371
  _globals['_CREATEURLRECORDREQUEST']._serialized_end=434
  _globals['_CREATEURLRECORDRESPONSE']._serialized_start=436
  _globals['_CREATEURLRECORDRESPONSE']._serialized_end=492
  _globals['_URLEXTENDEDSERVICE']._serialized_start=495
  _globals['_URLEXTENDEDSERVICE']._serialized_end=646
# @@protoc_insertion_point(module_scope)
